// <auto-generated />
using IIoT.Edge.Infrastructure.Persistence.EfCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IIoT.Edge.Infrastructure.Persistence.EfCore.Migrations
{
    [DbContext(typeof(EdgeDbContext))]
    partial class EdgeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("IIoT.Edge.Domain.Config.Aggregates.DeviceParamEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("MaxValue")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("max_value");

                    b.Property<string>("MinValue")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("min_value");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("NetworkDeviceId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("network_device_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sort_order");

                    b.Property<string>("Unit")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("unit");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("NetworkDeviceId")
                        .HasDatabaseName("ix_cfg_device_param_device_id");

                    b.ToTable("cfg_device_param", (string)null);
                });

            modelBuilder.Entity("IIoT.Edge.Domain.Config.Aggregates.SystemConfigEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sort_order");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ix_cfg_system_config_key");

                    b.ToTable("cfg_system_config", (string)null);
                });

            modelBuilder.Entity("IIoT.Edge.Domain.Hardware.Aggregates.IoMappingEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("AddressCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("address_count");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("data_type");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("direction");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("label");

                    b.Property<int>("NetworkDeviceId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("network_device_id");

                    b.Property<string>("PlcAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("plc_address");

                    b.Property<string>("Remark")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("remark");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("NetworkDeviceId")
                        .HasDatabaseName("ix_hw_io_mapping_network_device_id");

                    b.ToTable("hw_io_mapping", (string)null);
                });

            modelBuilder.Entity("IIoT.Edge.Domain.Hardware.Aggregates.NetworkDeviceEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("ConnectTimeout")
                        .HasColumnType("INTEGER")
                        .HasColumnName("connect_timeout");

                    b.Property<string>("DeviceModel")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("device_model");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("device_name");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("device_type");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("ip_address");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_enabled");

                    b.Property<int>("Port1")
                        .HasColumnType("INTEGER")
                        .HasColumnName("port1");

                    b.Property<int?>("Port2")
                        .HasColumnType("INTEGER")
                        .HasColumnName("port2");

                    b.Property<string>("Remark")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("remark");

                    b.Property<string>("SendCmd1")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("send_cmd1");

                    b.Property<string>("SendCmd2")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("send_cmd2");

                    b.HasKey("Id");

                    b.HasIndex("IpAddress")
                        .HasDatabaseName("ix_hw_network_device_ip");

                    b.ToTable("hw_network_device", (string)null);
                });

            modelBuilder.Entity("IIoT.Edge.Domain.Hardware.Aggregates.SerialDeviceEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("BaudRate")
                        .HasColumnType("INTEGER")
                        .HasColumnName("baud_rate");

                    b.Property<int>("DataBits")
                        .HasColumnType("INTEGER")
                        .HasColumnName("data_bits");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("device_name");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("device_type");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_enabled");

                    b.Property<string>("Parity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("parity");

                    b.Property<string>("PortName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("port_name");

                    b.Property<string>("Remark")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("remark");

                    b.Property<string>("SendCmd1")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("send_cmd1");

                    b.Property<string>("SendCmd2")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("send_cmd2");

                    b.Property<string>("StopBits")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("stop_bits");

                    b.HasKey("Id");

                    b.HasIndex("PortName")
                        .HasDatabaseName("ix_hw_serial_device_port_name");

                    b.ToTable("hw_serial_device", (string)null);
                });

            modelBuilder.Entity("IIoT.Edge.Domain.Config.Aggregates.DeviceParamEntity", b =>
                {
                    b.HasOne("IIoT.Edge.Domain.Hardware.Aggregates.NetworkDeviceEntity", "NetworkDevice")
                        .WithMany()
                        .HasForeignKey("NetworkDeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NetworkDevice");
                });

            modelBuilder.Entity("IIoT.Edge.Domain.Hardware.Aggregates.IoMappingEntity", b =>
                {
                    b.HasOne("IIoT.Edge.Domain.Hardware.Aggregates.NetworkDeviceEntity", "NetworkDevice")
                        .WithMany("IoMappings")
                        .HasForeignKey("NetworkDeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NetworkDevice");
                });

            modelBuilder.Entity("IIoT.Edge.Domain.Hardware.Aggregates.NetworkDeviceEntity", b =>
                {
                    b.Navigation("IoMappings");
                });
#pragma warning restore 612, 618
        }
    }
}
